// playwright-cli run-code --filename; record actual animations, mock assistant traffic.
async page => {
  await page.unrouteAll({ behavior: 'ignoreErrors' });
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1280, height: 650 });
  const origin = new URL(page.url()).origin;
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.addInitScript(() => {
    if (window.pageMotionInstrumented) return;
    window.pageMotionInstrumented = true;
    window.pageEntrances = [];
    const animate = Element.prototype.animate;
    Element.prototype.animate = function (...args) {
      const animation = animate.apply(this, args);
      if (this.id === 'main-content') window.pageEntrances.push({ path: location.pathname, pending: !!this.querySelector('[data-navigation-pending]'), scroll: scrollY, animation });
      return animation;
    };
  });
  await page.route('**/api/assistant/status', r => r.fulfill({ json: { status: 'ready', message: '' } }));
  await page.route('**/api/model-connections**', r => r.fulfill({ json: { provider: 'deepseek', deepseek: { configured: true, model: 'test', models: [{ id: 'test', name: 'Test' }] }, chatgpt: { configured: false, models: [] } } }));
  await page.route('**/api/assistant/sessions**', r => r.fulfill({ json: { sessions: [], total: 0 } }));
  await page.goto(origin + '/settings');
  await page.getByRole('heading', { name: '设置', exact: true }).waitFor();
  const frames = () => page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  const count = () => page.evaluate(() => window.pageEntrances.length);
  const entered = async path => {
    await page.waitForFunction(path => window.pageEntrances.at(-1)?.path === path, path);
    await page.evaluate(async () => { await window.pageEntrances.at(-1).animation.finished.catch(() => {}); });
  };
  await frames();
  if (await count()) throw new Error('initial load should not animate');
  let release;
  const gate = new Promise(resolve => { release = resolve; });
  await page.route('**/src/pages/AboutPage.tsx*', async route => { await gate; await route.continue(); });
  await page.getByRole('link', { name: '关于', exact: true }).click();
  await page.locator('[data-navigation-pending]').waitFor();
  await frames();
  if (await count()) throw new Error('loading placeholder animated');
  release();
  await entered('/about');
  if (await count() !== 1 || await page.evaluate(() => window.pageEntrances[0].pending)) throw new Error('ready page must animate once');
  await page.getByRole('link', { name: '设置', exact: true }).click();
  await entered('/settings');
  const beforeCategory = await count();
  await page.getByRole('button', { name: '击拍精度', exact: true }).click();
  await frames();
  if (await count() !== beforeCategory) throw new Error('category change animated whole page');
  await page.getByRole('link', { name: '随机练习', exact: true }).click();
  await entered('/random/tapping');
  await page.getByRole('button', { name: '节奏听写', exact: true }).click();
  await entered('/random/dictation');
  await page.evaluate(() => scrollTo(0, 400));
  await frames();
  const scroll = await page.evaluate(() => scrollY);
  if (scroll < 50) throw new Error('scroll fixture too short');
  await page.getByRole('link', { name: '关于', exact: true }).click();
  await entered('/about');
  await page.goBack();
  await entered('/random/dictation');
  const restored = await page.evaluate(() => window.pageEntrances.at(-1).scroll);
  if (Math.abs(restored - scroll) > 2) throw new Error('entrance began before scroll restoration');
  await page.getByRole('button', { name: '打开 AI 助手' }).click();
  const input = page.getByRole('textbox', { name: '向助手提问' });
  await input.fill('转场保留草稿');
  await input.evaluate(e => { window.composerNode = e; });
  await page.getByRole('link', { name: '节奏助手', exact: true }).click();
  await page.locator('.assistant-workspace[data-home="true"]').waitFor();
  if (!await input.evaluate(e => e === window.composerNode) || await input.inputValue() !== '转场保留草稿') throw new Error('route animation remounted assistant');
  await page.getByRole('link', { name: '关于', exact: true }).click();
  await page.waitForFunction(() => window.pageEntrances.at(-1)?.path === '/about');
  await page.evaluate(() => { window.interruptedEntrance = window.pageEntrances.at(-1).animation; window.interruptedEntrance.pause(); });
  await page.getByRole('link', { name: '设置', exact: true }).click();
  await entered('/settings');
  if (await page.evaluate(() => window.interruptedEntrance.playState) !== 'idle') throw new Error('old entrance survived navigation');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const beforeReduced = await count();
  await page.getByRole('link', { name: '关于', exact: true }).click();
  await page.locator('.about-page').waitFor();
  await frames();
  if (await count() !== beforeReduced) throw new Error('reduced motion animated route');
  if (await page.locator('#main-content').evaluate(e => getComputedStyle(e).opacity) !== '1') throw new Error('page left transparent');
  if (errors.length) throw new Error(errors.join('\n'));
  await page.unrouteAll({ behavior: 'ignoreErrors' });
  return 'ready-only entrance, local update exclusion, history scroll, assistant continuity and reduced motion passed';
}
